name = "OMAS"
uuid = "38ff3f74-8a6b-4bc2-a5e1-5aa78a7f6049"
authors = ["Orso Meneghini <orso82@gmail.com>"]
version = "0.1.0"

[deps]
IMAS = "13ead8c1-b7d1-41bb-a6d0-5b8b65ed587a"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
PythonCall = "0.9.23"
